// Command voodu-postgres expands a `postgres "<scope>" "<name>" { … }`
// HCL block into a statefulset manifest.
//
// # Status: M-P0 (stub)
//
// This release parses + validates the operator's HCL and STOPS — no
// runtime manifest is emitted yet. Apply will fail loudly with a
// "not yet implemented" message that points at the next milestone.
//
// The full production-ready plugin (initdb, postgresql.conf
// bootstrap, streaming replication, WAL archive, failover,
// backup/restore) lands incrementally in M-P1..M-P6. See
// project_voodu_postgres_planning.md for the milestone breakdown.
//
// # Plugin contract
//
// stdin: { kind, scope, name, spec } — same shape voodu's
// controller persists for any kind.
//
// stdout (M-P0): error envelope when expand is called against a
// real apply, OK envelope when `defaults` is called for inspection.
//
// # Defaults (target shape, emitted by `defaults` subcommand)
//
//	image       = "postgres:latest"
//	replicas    = 1
//	database    = "postgres"
//	user        = "postgres"
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
)

var version = "dev"

const defaultImage = "postgres:latest"

type expandRequest struct {
	Kind  string          `json:"kind"`
	Scope string          `json:"scope,omitempty"`
	Name  string          `json:"name"`
	Spec  json.RawMessage `json:"spec,omitempty"`
}

type envelope struct {
	Status string `json:"status"`
	Data   any    `json:"data,omitempty"`
	Error  string `json:"error,omitempty"`
}

func main() {
	if len(os.Args) < 2 {
		emitErr("usage: voodu-postgres <expand|defaults|--version>")
		os.Exit(1)
	}

	switch os.Args[1] {
	case "--version", "-v", "version":
		fmt.Println(version)

	case "defaults":
		emitOK(composeDefaults())

	case "expand":
		if err := cmdExpand(); err != nil {
			emitErr(err.Error())
			os.Exit(1)
		}

	default:
		emitErr(fmt.Sprintf("unknown subcommand %q (want expand|defaults)", os.Args[1]))
		os.Exit(1)
	}
}

// cmdExpand is the M-P0 stub. It still parses + validates the
// operator's HCL block (so misconfigurations surface at apply
// time) but deliberately refuses to emit a runtime manifest —
// that lands in M-P1.
//
// Returning a hard error here is intentional: it stops `vd apply`
// from proceeding and prints a clear pointer at the milestone
// that wires up actual statefulset emission. Same pattern voodu-
// redis used during M-S0 of its Sentinel rollout.
func cmdExpand() error {
	raw, err := io.ReadAll(os.Stdin)
	if err != nil {
		return fmt.Errorf("read stdin: %w", err)
	}

	var req expandRequest
	if err := json.Unmarshal(raw, &req); err != nil {
		return fmt.Errorf("decode expand request: %w", err)
	}

	if req.Name == "" {
		return fmt.Errorf("expand request missing required field 'name'")
	}

	var operatorSpec map[string]any

	if len(req.Spec) > 0 {
		if err := json.Unmarshal(req.Spec, &operatorSpec); err != nil {
			return fmt.Errorf("decode block spec: %w", err)
		}
	}

	spec, err := parsePostgresSpec(operatorSpec)
	if err != nil {
		return fmt.Errorf("postgres %s: %w", refOrName(req.Scope, req.Name), err)
	}

	if err := validatePostgresSpec(spec); err != nil {
		return fmt.Errorf("postgres %s: %w", refOrName(req.Scope, req.Name), err)
	}

	return fmt.Errorf(
		"postgres %s: HCL parsed and validated (image=%s, replicas=%d, database=%s, user=%s, port=%d, extensions=%d, pg_config_keys=%d), "+
			"but runtime emission is not yet implemented (lands in M-P1 of voodu-postgres). "+
			"Track plugin v0.3.x for the first production-ready release.",
		refOrName(req.Scope, req.Name),
		spec.Image,
		spec.Replicas,
		spec.Database,
		spec.User,
		spec.Port,
		len(spec.Extensions),
		len(spec.PgConfig),
	)
}

// composeDefaults returns the target default shape the plugin
// will emit once M-P1 lands. In M-P0 it's only used by the
// `defaults` subcommand for inspection — it does NOT feed expand.
func composeDefaults() map[string]any {
	return map[string]any{
		"image":           defaultImage,
		"replicas":        1,
		"database":        "postgres",
		"user":            "postgres",
		"password":        "<auto-generated 32 chars on first boot>",
		"port":            5432,
		"initdb_locale":   "C.UTF-8",
		"initdb_encoding": "UTF8",
		"pg_config":       map[string]any{},
		"extensions":      []any{},
	}
}

func emitOK(data any) {
	enc := json.NewEncoder(os.Stdout)

	_ = enc.Encode(envelope{Status: "ok", Data: data})
}

func emitErr(msg string) {
	enc := json.NewEncoder(os.Stderr)

	_ = enc.Encode(envelope{Status: "error", Error: msg})
}
