// Tests for renderPgOverridesConf — the pure function that turns
// `pg_config = { ... }` into postgresql.conf bytes. Pinning what
// matters operationally:
//
//   - Empty / nil input still produces a header (asset emits the
//     file unconditionally; wrapper symlinks it always).
//   - Output ordering is alphabetical by key — stable across map
//     iteration, so asset digests don't flap on re-applies.
//   - Type-specific formatting: ints unquoted, bools `on`/`off`,
//     strings single-quoted with SQL-style '' escaping.
//   - Float values with whole-number magnitude render as ints
//     (max_connections = 200, not 200.000000).

package main

import (
	"strings"
	"testing"
)

func TestRenderPgOverridesConf_EmptyMapReturnsHeaderOnly(t *testing.T) {
	got := renderPgOverridesConf(nil)

	if !strings.Contains(got, "generated by voodu-postgres") {
		t.Errorf("missing header on empty map:\n%s", got)
	}

	// No directive lines should appear — only header comments.
	for _, line := range strings.Split(got, "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}

		t.Errorf("unexpected non-comment line on empty map: %q", line)
	}
}

func TestRenderPgOverridesConf_EmptyMapEqualsNilMap(t *testing.T) {
	if renderPgOverridesConf(nil) != renderPgOverridesConf(map[string]any{}) {
		t.Error("nil map and empty map should render identically")
	}
}

func TestRenderPgOverridesConf_AlphabeticalOrder(t *testing.T) {
	// Map iteration is randomised in Go, so we have to sort keys
	// for stable asset bytes. Pinned by checking that running the
	// same input twice gives identical output AND the first key
	// appears before the last key.
	in := map[string]any{
		"zoo":          1,
		"alpha":        2,
		"middle_thing": 3,
	}

	got := renderPgOverridesConf(in)

	// Determinism: two calls = same bytes.
	if renderPgOverridesConf(in) != got {
		t.Error("output not stable across calls (map iteration leaked)")
	}

	alphaIdx := strings.Index(got, "alpha")
	zooIdx := strings.Index(got, "zoo")

	if alphaIdx < 0 || zooIdx < 0 {
		t.Fatalf("missing keys in output:\n%s", got)
	}

	if alphaIdx > zooIdx {
		t.Errorf("expected alphabetical order (alpha before zoo):\n%s", got)
	}
}

func TestRenderPgOverridesConf_IntegerValues(t *testing.T) {
	got := renderPgOverridesConf(map[string]any{
		"max_connections": 200,
		"work_mem_mb":     int64(16),
	})

	wantLines := []string{"max_connections = 200", "work_mem_mb = 16"}

	for _, want := range wantLines {
		if !strings.Contains(got, want) {
			t.Errorf("expected %q in:\n%s", want, got)
		}
	}
}

func TestRenderPgOverridesConf_FloatWholeRendersAsInteger(t *testing.T) {
	// JSON decode gives float64 for any number; whole-magnitude
	// floats must NOT render as 200.000000 — operators write
	// `max_connections = 200` and expect that back.
	got := renderPgOverridesConf(map[string]any{
		"max_connections": float64(200),
	})

	if !strings.Contains(got, "max_connections = 200\n") {
		t.Errorf("expected `max_connections = 200`, got:\n%s", got)
	}

	if strings.Contains(got, "200.0") {
		t.Errorf("float should render as integer when whole-magnitude:\n%s", got)
	}
}

func TestRenderPgOverridesConf_FractionalFloat(t *testing.T) {
	got := renderPgOverridesConf(map[string]any{
		"random_page_cost": 1.5,
	})

	if !strings.Contains(got, "random_page_cost = 1.5") {
		t.Errorf("fractional float not rendered:\n%s", got)
	}
}

func TestRenderPgOverridesConf_BoolValues(t *testing.T) {
	// Postgres prefers on/off (matches what `SHOW` emits) — true/false
	// also work but on/off is the convention.
	got := renderPgOverridesConf(map[string]any{
		"log_connections":    true,
		"log_disconnections": false,
	})

	if !strings.Contains(got, "log_connections = on") {
		t.Errorf("bool true should be `on`:\n%s", got)
	}

	if !strings.Contains(got, "log_disconnections = off") {
		t.Errorf("bool false should be `off`:\n%s", got)
	}
}

func TestRenderPgOverridesConf_StringValuesSingleQuoted(t *testing.T) {
	got := renderPgOverridesConf(map[string]any{
		"shared_buffers": "256MB",
	})

	if !strings.Contains(got, "shared_buffers = '256MB'") {
		t.Errorf("string should be single-quoted:\n%s", got)
	}
}

func TestRenderPgOverridesConf_EscapeSingleQuotesInStrings(t *testing.T) {
	// Postgres's GUC string escape doubles the quote. Anti-injection:
	// without this, `pg_config = { foo = "a' bad value" }` could
	// inject a directive break.
	got := renderPgOverridesConf(map[string]any{
		"some_string": "a's value",
	})

	if !strings.Contains(got, "some_string = 'a''s value'") {
		t.Errorf("expected SQL-style single-quote escape:\n%s", got)
	}
}

func TestQuotePgString(t *testing.T) {
	cases := []struct {
		in   string
		want string
	}{
		{"", "''"},
		{"abc", "'abc'"},
		{"with 'quote'", "'with ''quote'''"},
		{"trailing'", "'trailing'''"},
	}

	for _, tc := range cases {
		got := quotePgString(tc.in)
		if got != tc.want {
			t.Errorf("quotePgString(%q): got %q, want %q", tc.in, got, tc.want)
		}
	}
}
