// pg_config map → postgresql.conf bytes. Pure function, called by
// cmdExpand to materialise the asset's overrides file.
//
// Why a dedicated file: rendering keeps growing as we honour more
// pg_config types (numbers, durations, booleans, strings with
// special chars). Isolating the logic from cmdExpand keeps the
// emit path readable and unit-testable.

package main

import (
	"fmt"
	"sort"
	"strings"
)

// renderPgOverridesConf turns the operator's `pg_config = { ... }`
// map into postgresql.conf bytes. Output shape:
//
//	# generated by voodu-postgres
//	# pg_config overrides from HCL — do not edit in place
//	max_connections = 200
//	shared_buffers = '256MB'
//	log_connections = on
//
// Format rules:
//
//   - Integer / float values pass through unquoted (postgres parses
//     them as numbers).
//   - Bool values render as `on` / `off` (the postgres convention;
//     `true`/`false` also work but `on`/`off` is what postgres
//     emits in `SHOW`).
//   - String values are wrapped in single quotes. Embedded single
//     quotes are escaped as '' (the postgres SQL convention,
//     which also applies to GUCs).
//   - Anything else stringifies via fmt.Sprintf("%v") and gets
//     single-quoted defensively.
//
// Keys are sorted alphabetically so the asset bytes are stable
// across map-iteration order — same input always yields same
// digest, no spurious rolling restarts on replays.
//
// Empty map (nil or len 0) returns just the header comments — the
// asset still emits a file (the wrapper symlinks it
// unconditionally), it just doesn't override any parameters.
func renderPgOverridesConf(pgConfig map[string]any) string {
	var b strings.Builder

	b.Grow(256 + len(pgConfig)*48)

	b.WriteString("# generated by voodu-postgres\n")
	b.WriteString("# pg_config overrides from HCL — do not edit in place\n")
	b.WriteString("# (regenerated on every apply; operator changes lost)\n")

	if len(pgConfig) == 0 {
		return b.String()
	}

	keys := make([]string, 0, len(pgConfig))
	for k := range pgConfig {
		keys = append(keys, k)
	}

	sort.Strings(keys)

	for _, k := range keys {
		b.WriteString(k)
		b.WriteString(" = ")
		b.WriteString(formatPgConfigValue(pgConfig[k]))
		b.WriteByte('\n')
	}

	return b.String()
}

// formatPgConfigValue renders one HCL value as a postgresql.conf
// right-hand side. See renderPgOverridesConf for the format rules.
func formatPgConfigValue(v any) string {
	switch x := v.(type) {
	case bool:
		if x {
			return "on"
		}

		return "off"

	case int:
		return fmt.Sprintf("%d", x)

	case int64:
		return fmt.Sprintf("%d", x)

	case float64:
		// HCL/JSON give us float64 for any number; preserve
		// integer-valued floats as integers so the .conf reads
		// like the operator wrote it (max_connections = 200, not
		// max_connections = 200.000000).
		if x == float64(int64(x)) {
			return fmt.Sprintf("%d", int64(x))
		}

		return fmt.Sprintf("%g", x)

	case string:
		return quotePgString(x)

	default:
		// Defensive: stringify whatever it is and quote it.
		// Validation already rejects non-scalar pg_config values
		// at parse time, so this is mostly belt-and-suspenders
		// for future map/list values that might slip through.
		return quotePgString(fmt.Sprintf("%v", v))
	}
}

// quotePgString wraps a string value in single quotes, escaping any
// embedded single quote per postgres's GUC string syntax (doubled
// single-quote, same as SQL string literals).
func quotePgString(s string) string {
	if !strings.ContainsRune(s, '\'') {
		return "'" + s + "'"
	}

	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}
